apiVersion: apps/v1
kind: Deployment
metadata:
  name: hola-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hola-pod
  template:
    metadata:
      labels:
        app: hola-pod
    spec:
      containers:
        - name: hola-pod
          image: quay.io/martinezj/demo-ocp:fcf8870c0d77fa6a3ac0362e8cdb9a1c0caa65d5
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: secret-registry
